services:
  tautulli:
    container_name: tautulli
    image: ghcr.io/hotio/tautulli
    restart: unless-stopped
    ports:
      - 8181:8181
    volumes:
      - /home/kysfu/tautulli/config:/config
networks: {}
