services:
  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /home/kysfu/overseerr/config:/config
