services:
  overseerr:
    restart: unless-stopped
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    ports:
      - 5055:5055
    volumes:
      - /home/kysfu/overseerr/config:/config
networks: {}
