services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    volumes:
      - /home/kysfu/prowlarr/config:/config
networks: {}
