services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /home/kysfu/plex/config:/config
      - /media/12TB3:/12TB3
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
