services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /home/kysfu/plex/config:/config
      - /home/kysfu/plex/transcode:/transcode #transcode temp directory
      - /media/4TB:/data/4TB
      - /media/8TB:/data/8TB
      - /media/8TB2:/data/8TB2
      - /media/10TB:/data/10TB
      - /media/10TB2:/data/10TB2
      - /media/12TB:/data/12TB
      - /media/12TB2:/data/12TB2
      - /media/12TB3:/data/12TB3
      - /media/14TB:/data/14TB
      - /media/14TB2:/data/14TB2
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri #passthrough for Intel QuickSync
