services:
  #username:admin@example.com
  #password:password
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=kysfu
      - DB_PASSWORD=Niceguy58570!
    volumes:
      - /home/kysfu/speedtest-tracker/config:/config
      - /home/kysfu/tautulli/config/keys:/config/keys
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mariadb:10
    restart: always
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=kysfu
      - MARIADB_PASSWORD=Niceguy58570!
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:
