version: "3.3"
services:
  watchtower:
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://7842679587:AAFBqfCngc3MIrqQWl3voGfffoUyvEAcwTA@telegram/?channels=5835308973
      - WATCHTOWER_CLEANUP=true # optional. Remove old images after updating
networks: {}
