services:
  portainer-ce:
    ports:
      - 9000:9000
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/kysfu/portainer/data:/data
    image: portainer/portainer-ce
