services:
  portainer:
    ports:
      - 8000:8000
      - 9443:9443
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/kysfu/portainer/data:/data
    image: portainer/portainer-ce:latest
volumes:
  portainer_data: {}
