services:
  vrising:
    container_name: vrising
    image: trueosiris/vrising
    environment:
      - TZ=America/Chicago
      - SERVERNAME=Kysfu V Rising Server
    volumes:
      - type: bind
        source: /home/kysfu/vrising/server
        target: /mnt/vrising/server
        bind:
          create_host_path: true
      - type: bind
        source: /home/kysfu/vrising/persistentdata
        target: /mnt/vrising/persistentdata
        bind:
          create_host_path: true
    ports:
      - 9876:9876/udp
      - 9877:9877/udp
    restart: unless-stopped
    network_mode: bridge
